# Generated by Django 6.0.1 on 2026-01-29 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Drame", "Drame"),
                            ("Comédie", "Comédie"),
                            ("Horreur", "Horreur"),
                            ("Romance", "Romance"),
                            ("Comédie musicale", "Comédie musicale"),
                            ("Guerre", "Guerre"),
                            ("Science-Fiction", "Science-Fiction"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=50,
                    ),
                ),
                ("duree", models.PositiveIntegerField(help_text="Durée en minutes")),
                ("date_sortie", models.DateField(blank=True, null=True)),
                (
                    "affiche",
                    models.ImageField(blank=True, null=True, upload_to="affiches/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=10)),
                ("nb_lignes", models.PositiveIntegerField(default=5)),
                ("nb_colonnes", models.PositiveIntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure", models.TimeField()),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seances",
                        to="Films.film",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Films.salle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Siege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ligne", models.PositiveIntegerField()),
                ("colonne", models.PositiveIntegerField()),
                ("est_reserve", models.BooleanField(default=False)),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Films.salle"
                    ),
                ),
            ],
            options={
                "unique_together": {("salle", "ligne", "colonne")},
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reservation", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Films.seance"
                    ),
                ),
                ("sieges", models.ManyToManyField(to="Films.siege")),
            ],
        ),
    ]
