# Generated by Django 6.0.1 on 2026-01-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Films", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siege",
            name="est_reserve",
        ),
    ]
